services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=roombooking_db
      - POSTGRES_USER=tu_admin
      - POSTGRES_PASSWORD=tu_password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=roombooking_db
      - DB_USER=tu_admin
      - DB_PASSWORD=tu_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: