# Generated by Django 6.0.3 on 2026-04-21 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อห้อง')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('capacity', models.IntegerField(verbose_name='ความจุ (คน)')),
                ('location', models.CharField(max_length=200, verbose_name='สถานที่')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพห้อง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'ห้อง',
                'verbose_name_plural': 'ห้อง',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='เวลาเริ่มต้น')),
                ('end_time', models.DateTimeField(verbose_name='เวลาสิ้นสุด')),
                ('purpose', models.TextField(verbose_name='วัตถุประสงค์การใช้')),
                ('status', models.CharField(choices=[('Pending', 'รออนุมัติ'), ('Approved', 'อนุมัติแล้ว'), ('Rejected', 'ปฏิเสธ'), ('Cancelled', 'ยกเลิก')], default='Pending', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='ความเห็นจากผู้ดูแล')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.room', verbose_name='ห้อง')),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจอง',
            },
        ),
    ]
