# Generated by Django 4.2.30 on 2026-04-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='class_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสวิชา'),
        ),
        migrations.AddField(
            model_name='booking',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อวิชา'),
        ),
        migrations.AddField(
            model_name='booking',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('BACHELOR_NORMAL', 'ปริญญาตรีภาคปกติ'), ('MASTER', 'ปริญญาโท'), ('TEP_TEPE', 'TEP-TEPE'), ('TU_PINE', 'TU-PINE')], max_length=50, null=True, verbose_name='หลักสูตร'),
        ),
        migrations.AddField(
            model_name='booking',
            name='days_of_week',
            field=models.JSONField(blank=True, null=True, verbose_name='วันที่ต้องการจอง (รายสัปดาห์)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='จองแบบรายสัปดาห์'),
        ),
        migrations.AddField(
            model_name='booking',
            name='objective_type',
            field=models.CharField(choices=[('TEACHING', 'สอนปกติ/ชดเชย/เสริม'), ('TRAINING', 'จัดอบรม/จัดติว'), ('GENERAL', 'ใช้งานทั่วไป')], default='GENERAL', max_length=20, verbose_name='ประเภทวัตถุประสงค์'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurring_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='สิ้นสุดการจองรายสัปดาห์เมื่อ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='training_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้ออบรม'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสห้อง'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('MEETING', 'ห้องประชุม'), ('CLASSROOM', 'ห้องเรียน')], default='MEETING', max_length=20, verbose_name='ประเภทห้อง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose',
            field=models.TextField(verbose_name='รายละเอียดวัตถุประสงค์'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'รอการอนุมัติ'), ('Approved', 'อนุมัติแล้ว'), ('Rejected', 'ปฏิเสธ'), ('Cancelled', 'ยกเลิก')], default='Pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
